name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dep
      run: sudo apt-get update && sudo apt-get -y install meson git ninja-build
    - name: clone lightbig
      run: git clone https://github.com/smurfd/lightbig src/lightbig
    - name: Build
      run: meson build
    - name: Compile
      run: ninja -C build
    - name: Test
      run: ninja -C build test -v