name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install gcc make git openssl
    - name: Generate cert debug
      run: sh lightssl/src/scripts/gen_cert_debug.sh
    - name: Compile
      run: make -Clightssl/src

  build-latest-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install gcc make git openssl
    - name: Generate cert debug
      run: sh lightssl/src/scripts/gen_cert_debug.sh
    - name: Compile
      run: make -Clightssl/src
