name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang meson git ninja-build openssl
    - name: Build
      run: CC=clang meson build
    - name: Generate cert
      run: sh example/gen_cert.sh
    - name: Install dependencies
      run: sudo apt-get -y remove openssl
    - name: Compile
      run: CC=clang ninja -C build
    - name: Test
      run: CC=clang ninja -C build test -v -d stats -d explain
