name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang cmake make git openssl
    - name: Build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild/debug -DCMAKE_C_COMPILER=clang
    - name: Generate cert debug
      run: sh src/scripts/gen_cert_debug.sh
    - name: Compile
      run: make -Cbuild/debug
    - name: Test
      run: make -Cbuild/debug test

  build-latest-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang cmake make git openssl
    - name: Build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild/debug -DCMAKE_C_COMPILER=clang
    - name: Generate cert debug
      run: sh src/scripts/gen_cert_debug.sh
    - name: Compile
      run: make -Cbuild/debug
    - name: Test
      run: make -Cbuild/debug test

  stdout-test1:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang
    - name: run
      run: echo "int main() {int i = 0;}"| clang -x c - -o - >&2 > aa.out && chmod +x ./aa.out && ./aa.out

  stdout-test2:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang
    - name: run
      run: echo "int main() {int i = 0;}"| clang -x c - -o - /dev/stdout > aa.out && chmod +x ./aa.out && ./aa.out
  
  stdout-test3:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang
    - name: run
      run: echo "int main() {int i = 0;}"| clang -x c - -o /dev/stdout > aa.out && chmod +x ./aa.out && ./aa.out
