name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang cmake make git openssl
    - name: Build
      run: cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -DCMAKE_C_COMPILER=clang
    - name: Generate cert
      run: sh src/example/gen_cert.sh
    - name: Compile
      run: make -Cbuild
    - name: Test
      run: make -Cbuild test

  build-release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install clang cmake make git openssl
    - name: Build
      run: cmake -DCMAKE_BUILD_TYPE=Release -Bbuild/release -DCMAKE_C_COMPILER=clang
    - name: Generate cert
      run: sh src/example/gen_cert.sh
    - name: Compile
      run: make -Cbuild/release
    - name: Test
      run: make -Cbuild/release test
