name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dep
      run: sudo apt update && sudo apt -y install meson git
    - name: clone lightbig
      run: git clone https://github.com/smurfd/lightbig src/lightbig
    - name: meson build
      run: meson build
    - name: cd build
      run: cd build
    - name: meson compile
      run: meson compile
